### ISSUE TITLE
Support for merged PacketPrint and PacketStream

### ISSUE THREAD

**Issue by imwhocodes** [eric-wieser/packet-io#4]
Hi

It is possible to have one single object that support both the functionalities of `PacketPrint` and `PacketStream`?
It would be useful to have a single abstraction that handle both sending and receiving COBS encoded data

Thanks,
Luca

**Comment by imwhocodes** [comment]
Is this project still alive?

**Comment by eric-wieser** [comment]
This was a conscious decision, similar to how `std::cout` and `std::cin` are entirely separate objects in C++.

> Is this project still alive?

Not really. I get 10s of notifications a day from active projects, so I missed these comments.
